# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        host: windows
        version: 5.11.3
        arch: win32_mingw53
        #modules: 'qtcore'
        extra: --external 7z

    - name: Check availability of libraries
      working-directory: D:/a/qt-github-console/Qt/5.11.3/mingw53_32/lib/
      run: |
        ls

    - name: Qmake and make
      working-directory: d:/a/qt-github-console/qt-github-console
      run: | 
        qmake.exe qt-github-console.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
        mingw32-make.exe qmake_all
        
    - name: Make mingw32
      working-directory: d:/a/qt-github-console/qt-github-console
      run: |
        mingw32-make.exe -j8
