name: CI

env:
  QT_VERSION:     "5.12.7"
  MINGW_VERSION:  "win32_mingw73"
  MINGW_PATH:     "mingw73_32"
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install correct version of mingw
      run: |
        choco uninstall mingw
        choco install mingw --version=7.3.0
  
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        host: windows
        version: ${{ env.QT_VERSION }}
        arch: ${{ env.MINGW_VERSION }}
        #modules: 'qtcore'
        extra: --external 7z

    - name: Check availability of libraries
      working-directory: D:/a/qt-github-console/Qt/${{ env.QT_VERSION }}/${{ env.MINGW_PATH }}/lib/
      run: |
        ls

    - name: Qmake and make
      working-directory: d:/a/qt-github-console/qt-github-console
      run: | 
        qmake.exe qt-github-console.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
        mingw32-make.exe qmake_all
        
    - name: Make mingw32
      working-directory: d:/a/qt-github-console/qt-github-console
      run: |
        mingw32-make.exe -j8
